Repository bagherilab/ARCADE, pull requests merged in 2025-04, with the labels that each got.

#173 Add swapVoxels function to PottsLocation
  src/arcade/potts/env/location/PottsLocation.java
  test/arcade/potts/env/location/PottsLocationTest.java
Labels: priority: high, type: feature, package: potts, category: env, size: small

#179 Delete redundant parameter in parameter.patch.xml
  src/arcade/patch/parameter.patch.xml
Labels: size: xsmall

#180 Bump JDK image version in dockerfile
  Dockerfile
Labels: type: admin, size: xsmall
